#!/bin/bash

vel=($(grep "internalField " 0/U | awk -F "[()]" '{print $2}'))

u=${vel[0]}
v=${vel[1]}


n=`echo "sqrt($u*$u + $v*$v)" | bc -l | awk '{printf "%f", $0}'`
nj=`echo "$v/$n" |bc -l | awk '{printf "%f", $0}'`
ni=`echo "$u/$n" |bc -l | awk '{printf "%f", $0}'`

#echo $ni, $nj, $n

sed -i 's/liftDir.*/liftDir ( -'$nj' '$ni' 0 );/' system/controlDict
sed -i 's/dragDir.*/dragDir ( '$ni' '$nj' 0 );/' system/controlDict
sed -i 's/magUInf.*/magUInf '$n';/' system/controlDict
